import type { ResearchSourceId, ResearchSourceRecord } from "./researchDataTypes";

export const researchDataSources3: Record<ResearchSourceId, ResearchSourceRecord> = {
  SE35: { title: "Cohen — Federal CSEM Supervision Risk Tool", organization: "Federal Probation / U.S. Courts", type: "Government journal article", href: "https://www.uscourts.gov/about-federal-courts/probation-and-pretrial-services/federal-probation-journal/2023/06/building-a-risk-tool-persons-placed-federal-post-conviction-supervision-child-sexual-exploitation", usefulFor: "Federal CSEM supervision research on rearrest outcomes, PCRA, CPORT, and the limits of transporting general-risk scores into specialized sexual-risk decisions." },
  SE36: { title: "BJS — Sex-Offender Recidivism, 9-Year Follow-Up", organization: "Bureau of Justice Statistics", type: "Government statistical report", href: "https://bjs.ojp.gov/library/publications/recidivism-sex-offenders-released-state-prison-9-year-follow-2005-14", usefulFor: "Longer-term comparison of rape and sexual-assault release groups with other released prisoners, including overall and sexual rearrest outcomes." },
  SE37: { title: "BJS — Prisoner Recidivism, 2012 Releases", organization: "Bureau of Justice Statistics", type: "Government statistical report", href: "https://bjs.ojp.gov/sites/g/files/xyckuh236/files/media/document/rpr34s125yfup1217.pdf", usefulFor: "Five-year same-type rearrest comparisons across release-offense categories and evidence about offense specialization." },
  SE38: { title: "BJS — Prisoner Recidivism, 1994 Specialization", organization: "Bureau of Justice Statistics", type: "Government statistical report", href: "https://bjs.ojp.gov/content/pub/pdf/rpr94.pdf", usefulFor: "Same-offense rearrest patterns across multiple crime categories, useful for comparing specialization rather than assuming recurrence is unique to sexual offending." },
  SE39: { title: "USSC — Federal Offenders Released in 2010", organization: "U.S. Sentencing Commission", type: "Federal government research report", href: "https://www.ussc.gov/sites/default/files/pdf/research-and-publications/research-publications/2021/20210930_Recidivism.pdf", usefulFor: "Same-cohort federal recidivism evidence by offense type, age, and criminal history for comparative and individualized-risk analysis." },
  SE40: { title: "Sandler, Freeman & Socia — New York SORN", organization: "Peer-reviewed research", type: "Peer-reviewed article", href: "https://doi.org/10.1037/a0013881", usefulFor: "New York time-series evidence on SORN outcomes, including the predominance of first-time sex-offense arrests and tests of registry effectiveness." },
  SE41: { title: "Levenson & Zgoba — Florida Repeat-Arrest Study", organization: "Peer-reviewed research", type: "Peer-reviewed article", href: "https://doi.org/10.1177/0306624X15573946", usefulFor: "Florida evidence that only a small share of sex-crime arrests involved people with a prior felony sex-crime conviction, informing first-time-versus-repeat offending claims." },
  SE42: { title: "Letourneau et al. — South Carolina Adult Recidivism", organization: "Peer-reviewed research", type: "Peer-reviewed article", href: "https://doi.org/10.1177/0887403409353148", usefulFor: "South Carolina research testing whether registration status predicted adult sexual recidivism." },
  SE43: { title: "New Jersey Megan's Law Evaluation", organization: "National Institute of Justice", type: "Government report", href: "https://nij.ojp.gov/library/publications/megans-law-assessing-practical-and-monetary-efficacy", usefulFor: "State evaluation of practical, monetary, and public-safety outcomes under New Jersey's Megan's Law." },
  SE44: { title: "Duwe & Donnay — Minnesota Level 3 Notification", organization: "Peer-reviewed research", type: "Peer-reviewed article", href: "https://doi.org/10.1111/j.1745-9125.2008.00114.x", usefulFor: "Evidence of favorable outcomes for targeted community notification among selected higher-risk Level 3 individuals, useful as an important boundary on broad anti-registry claims." },
  SE45: { title: "Levenson & Cotter — Megan's Law and Reintegration", organization: "Peer-reviewed research", type: "Peer-reviewed article", href: "https://scholars.lynn.edu/en/publications/the-effect-of-megans-law-on-sex-offender-reintegration/", usefulFor: "Survey evidence on housing, employment, threats, social effects, and reintegration burdens associated with public registration and notification." },
  SE46: { title: "Lasher & McGrath — Reintegration Review", organization: "Peer-reviewed research", type: "Peer-reviewed review", href: "https://doi.org/10.1177/0306624X10387524", usefulFor: "Quantitative review of community notification, reintegration, housing, employment, and psychological consequences." },
  SE47: { title: "Zandbergen & Hart — Residence Restrictions", organization: "Peer-reviewed research", type: "Peer-reviewed article", href: "https://www.ojp.gov/ncjrs/virtual-library/abstracts/reducing-housing-options-convicted-sex-offenders-investigating", usefulFor: "GIS evidence on how residence-restriction laws can sharply reduce lawful housing options." },
  SE48: { title: "SMART SOMAPI — Management Strategies", organization: "SMART Office, U.S. Department of Justice", type: "Government evidence synthesis", href: "https://www.smart.ojp.gov/somapi/chapter-8-sex-offender-management-strategies", usefulFor: "Federal synthesis on SORN, residence restrictions, supervision and management strategies, including evidence on unintended consequences and public-safety mechanisms." },
  SE49: { title: "Anderson & Sample — Public Awareness and Action", organization: "Peer-reviewed research", type: "Peer-reviewed article", href: "https://www.ojp.gov/ncjrs/virtual-library/abstracts/public-awareness-and-action-resulting-sex-offender-community", usefulFor: "Survey evidence distinguishing registry availability from actual public use, self-reported protective behavior, and measured crime reduction." },
  SE50: { title: "Bonnar-Kidd — SORN Public-Health Review", organization: "Peer-reviewed public-health research", type: "Peer-reviewed review", href: "https://pmc.ncbi.nlm.nih.gov/articles/PMC2820068/", usefulFor: "Open-access review of SORN prevention claims, unintended consequences, and public-health concerns." },
  SE51: { title: "Cubellis, Walfield & Harris — Law-Enforcement Perspectives", organization: "Peer-reviewed research", type: "Peer-reviewed article", href: "https://doi.org/10.1177/0306624X16667574", usefulFor: "Law-enforcement survey evidence on perceived effectiveness, implementation challenges, and the effects of increasingly large registries." },
};
