import type { ResearchSourceId, ResearchSourceRecord } from "./researchDataTypes";

export const researchDataSources1: Record<ResearchSourceId, ResearchSourceRecord> = {
  SE01: { title: "BJS — Sex-Offender Recidivism", organization: "Bureau of Justice Statistics", type: "Official data / government report", href: "https://bjs.ojp.gov/content/pub/pdf/rsorp94.pdf", usefulFor: "Comparing rearrest, reconviction, and same-type recidivism across offense categories and understanding how detected recidivism changes with the measure used." },
  SE02: { title: "SMART — Adult Sexual Recidivism", organization: "SMART Office, U.S. Department of Justice", type: "Government research brief", href: "https://smart.ojp.gov/sites/g/files/xyckuh231/files/media/document/recidivismofadultsexualoffenders.pdf", usefulFor: "Understanding sexual recidivism rates, subgroup differences, follow-up periods, measurement challenges, and how risk changes over time." },
  SE03: { title: "25-Year SORN Meta-Analysis", organization: "Journal of Experimental Criminology", type: "Peer-reviewed meta-analysis", href: "https://link.springer.com/article/10.1007/s11292-021-09480-z", usefulFor: "A major peer-reviewed synthesis of 25 years of research on whether broad registration and notification policies reduce recidivism." },
  SE04: { title: "Prescott & Rockoff — SORN Effects", organization: "The Journal of Law and Economics", type: "Peer-reviewed article", href: "https://doi.org/10.1086/658485", usefulFor: "Examining whether law-enforcement registration and public notification have different effects on offending, deterrence, and recidivism." },
  SE05: { title: "NIJ-Funded — South Carolina SORN Evaluation", organization: "University of South Carolina research team / NIJ-funded", type: "NIJ-funded research report", href: "https://www.ojp.gov/pdffiles1/nij/grants/231989.pdf", usefulFor: "A detailed South Carolina evaluation of SORN policy effects on sexual violence, recidivism, deterrence, and unintended consequences." },
  SE06: { title: "SMART/LOC — Registry Collateral Effects", organization: "Federal Research Division, Library of Congress, for the SMART Office", type: "Government evidence review", href: "https://smart.ojp.gov/media/document/6346", usefulFor: "Reviewing research on how registration and notification affect housing, employment, wellbeing, family relationships, and reintegration." },
  SE07: { title: "Levenson & Tewksbury — Family Collateral Harm", organization: "American Journal of Criminal Justice", type: "Peer-reviewed article", href: "https://doi.org/10.1007/s12103-008-9055-x", usefulFor: "Documenting spillover consequences experienced by spouses, children, and other family members of people required to register." },
  SE08: { title: "Levenson et al. — Residence Restrictions & Transience", organization: "Criminal Justice Policy Review", type: "Peer-reviewed article", href: "https://doi.org/10.1177/0887403413512326", usefulFor: "Examining the relationship between residence restrictions, housing availability, transience, and community stability." },
  SE09: { title: "Colorado SOMB — Residence-Restriction Safety", organization: "Colorado Sex Offender Management Board", type: "State government report", href: "https://www.ojp.gov/ncjrs/virtual-library/abstracts/report-safety-issues-raised-living-arrangements-and-location-sex", usefulFor: "Official Colorado analysis of safety issues surrounding living arrangements, residence restrictions, and community placement." },
  SE10: { title: "Human Rights Watch — No Easy Answers", organization: "Human Rights Watch", type: "Investigative / policy report", href: "https://www.hrw.org/report/2007/09/11/no-easy-answers/sex-offender-laws-us", usefulFor: "Historical and policy context on registration, notification, exclusion, collateral consequences, and the expansion of registry laws." },
  SE11: { title: "BJS — Sexual Assault of Young Children", organization: "Bureau of Justice Statistics", type: "Official data / government report", href: "https://bjs.ojp.gov/content/pub/pdf/saycrle.pdf", usefulFor: "Official data on who commits reported sexual assaults against young children, including the predominance of family members and acquaintances over strangers." },
  SE12: { title: "OJJDP — Child Maltreatment Perpetrators", organization: "Office of Juvenile Justice and Delinquency Prevention", type: "Official data explainer", href: "https://ojjdp.ojp.gov/statistical-briefing-book/victims/faqs/qa02111", usefulFor: "Understanding the family, caregiver, and known-person context in which much child maltreatment occurs." },
  SE13: { title: "ED — Educator Sexual Misconduct", organization: "U.S. Department of Education", type: "Government research synthesis", href: "https://www.ed.gov/research/educator-sexual-misconduct-a-synthesis-of-existing-literature", usefulFor: "Understanding trusted access, authority, grooming, reporting, and safeguarding issues in school settings." },
  SE14: { title: "DOJ OIG — Larry Nassar Investigation", organization: "U.S. Department of Justice Office of Inspector General", type: "Inspector General report", href: "https://oig.justice.gov/sites/default/files/reports/21-093.pdf", usefulFor: "A documented case study of institutional failure after credible abuse allegations and the consequences of delayed action." },
  SE15: { title: "CDC — Firearm Injury & Death", organization: "Centers for Disease Control and Prevention", type: "Official data explainer", href: "https://www.cdc.gov/firearm-violence/data-research/facts-stats/index.html", usefulFor: "Official public-health data for comparing the scale of serious harms and the prevention systems used to address them." },
  SE16: { title: "NHTSA — Impaired-Driving Prevention", organization: "National Highway Traffic Safety Administration", type: "Government report", href: "https://www.nhtsa.gov/sites/nhtsa.gov/files/2026-03/Report-to-Congress-Advanced-Impaired-Driving-Prevention-Technology.pdf", usefulFor: "Showing how a recurring public-safety harm is addressed through prevention, technology, enforcement, research, and intervention." },
  SE17: { title: "BJS — Domestic Violence", organization: "Bureau of Justice Statistics", type: "Official data / government report", href: "https://bjs.ojp.gov/content/pub/pdf/ndv0312.pdf", usefulFor: "Official victimization data on another serious and often underreported form of interpersonal harm." },
  SE18: { title: "Smith v. Doe", organization: "U.S. Supreme Court", type: "Supreme Court decision", href: "https://supreme.justia.com/cases/federal/us/538/84/", usefulFor: "The central constitutional baseline for the Supreme Court's civil-regulatory treatment of Alaska's registry in ex post facto analysis." },
};
