import type { ResearchSourceId, ResearchSourceRecord } from "./researchDataTypes";

export const researchDataSources2: Record<ResearchSourceId, ResearchSourceRecord> = {
  SE19: { title: "Packingham v. North Carolina", organization: "U.S. Supreme Court", type: "Supreme Court decision", href: "https://supreme.justia.com/cases/federal/us/582/15-1194/", usefulFor: "Understanding constitutional limits on broad registry-related restrictions and the continuing rights of people with convictions." },
  SE20: { title: "GAO — SORNA Implementation", organization: "U.S. Government Accountability Office", type: "Government report", href: "https://www.gao.gov/assets/gao-13-211.pdf", usefulFor: "Implementation history, jurisdictional challenges, claimed benefits, burdens, and practical consequences of SORNA compliance." },
  SE21: { title: "ATSA — Evidence-Based Registry Reform", organization: "Association for the Treatment and Prevention of Sexual Abuse", type: "Expert policy recommendations", href: "https://members.atsa.com/learn/Details/report-registration-and-community-notification-of-adults-convicted-of-a-sexual-crime-recommendations-for-evidence-based-reform-194317", usefulFor: "Evidence-based recommendations for individualized risk assessment, treatment, review, reintegration, registration, and community notification policy." },
  SE22: { title: "Hanson et al. — Risk Declines Over Time", organization: "Peer-reviewed research", type: "Peer-reviewed study / PubMed index", href: "https://pubmed.ncbi.nlm.nih.gov/24664250/", usefulFor: "Evidence that recidivism risk can decline substantially with sustained offense-free time in the community." },
  SE23: { title: "SMART — Treatment Effectiveness", organization: "SMART Office, U.S. Department of Justice", type: "Government research brief", href: "https://smart.ojp.gov/sites/g/files/xyckuh231/files/media/document/theeffectivenessoftreatmentforadultsexualoffenders.pdf", usefulFor: "A federal synthesis of treatment research and its relationship to risk reduction, rehabilitation, and prevention." },
  SE24: { title: "Housing Instability Among Veterans", organization: "Peer-reviewed research", type: "Peer-reviewed study / PubMed index", href: "https://pubmed.ncbi.nlm.nih.gov/32960141/", usefulFor: "Quantitative evidence on the association between registered-sex-offender status and housing instability or homelessness in a large veteran population." },
  SE25: { title: "NSVRC — SART Prevention Toolkit", organization: "National Sexual Violence Resource Center", type: "Victim-prevention / nonprofit resource", href: "https://www.nsvrc.org/sarts/toolkit/7-4/", usefulFor: "Connecting sexual-violence response to broader prevention, survivor support, multidisciplinary practice, and community safety." },
  SE26: { title: "The Marshall Project — Banished", organization: "The Marshall Project", type: "Investigative media / illustrative case", href: "https://www.themarshallproject.org/2018/10/03/banished", usefulFor: "A concrete Miami-Dade illustration of displacement and homelessness produced by layered residence restrictions." },
  SE27: { title: "SMART — 2025 Case Law Summary", organization: "SMART Office, U.S. Department of Justice", type: "Government legal summary", href: "https://smart.ojp.gov/sorna/current-law/case-law/introduction", usefulFor: "Orientation to registry litigation, constitutional doctrine, and lower-court developments current through July 2025." },
  SE28: { title: "Banishment by a Thousand Laws", organization: "Washington University Law Review", type: "Law review article", href: "https://openscholarship.wustl.edu/law_lawreview/vol85/iss1/3/", usefulFor: "Legal and policy analysis of residence restrictions, exclusion zones, cumulative burdens, and modern banishment theory." },
  SE29: { title: "USSC — Non-Production Study (2021)", organization: "U.S. Sentencing Commission", type: "Government research report", href: "https://www.ussc.gov/research/research-reports/federal-sentencing-child-pornography-non-production-offenses", usefulFor: "Federal non-production recidivism data, including the finding that 4.3% of the studied cohort was rearrested for a sex offense within three years." },
  SE30: { title: "USSC — CP Recidivism Study (2012)", organization: "U.S. Sentencing Commission", type: "Government research report", href: "https://www.ussc.gov/sites/default/files/pdf/news/congressional-testimony-and-reports/sex-offense-topics/201212-federal-child-pornography-offenses/Chapter_11.pdf", usefulFor: "Longer-follow-up federal non-production recidivism data, including known sexual and contact-sexual recidivism and comparisons with contact-offender cohorts." },
  SE31: { title: "Agan — Fear without Function?", organization: "The Journal of Law and Economics", type: "Peer-reviewed study", href: "https://www.journals.uchicago.edu/doi/abs/10.1086/658483", usefulFor: "Testing registry effectiveness across three empirical designs, including state-level sexual-offense rates, post-release recidivism, and whether registry locations predict where sexual abuse occurs." },
  SE32: { title: "Hanson et al. — Once a Sexual Offender, Not Always", organization: "Psychology, Public Policy, and Law", type: "Peer-reviewed study", href: "https://doi.org/10.1037/law0000135", usefulFor: "Long-term evidence that sexual recidivism risk declines with sustained offense-free time across age and initial-risk groups, supporting reviewable policies that recognize desistance." },
  SE33: { title: "Thornton et al. — Residual Risk", organization: "Sexual Abuse", type: "Peer-reviewed study / PubMed index", href: "https://pubmed.ncbi.nlm.nih.gov/31478439/", usefulFor: "Showing how evaluators can incorporate offense-free time into individualized estimates of lifetime, residual, and year-by-year sexual recidivism risk." },
  SE34: { title: "Hanson, Lee & Thornton — High-Risk Long-Term Recidivism", organization: "Sexual Abuse", type: "Peer-reviewed study / PubMed index", href: "https://pubmed.ncbi.nlm.nih.gov/36382622/", usefulFor: "Long-term evidence from a deliberately high-risk sample showing substantial heterogeneity in risk while also examining how residual risk changes after extended offense-free periods." },
};
