import type { ResearchSourceId, ResearchSourceRecord } from "./researchDataTypes";

export const researchDataSources4: Record<ResearchSourceId, ResearchSourceRecord> = {
  SE52: { title: "Harris et al. — Registry Effectiveness and Challenges", organization: "Peer-reviewed research", type: "Peer-reviewed article", href: "https://doi.org/10.1177/0887403416651671", usefulFor: "National law-enforcement research on registry reliability, public utility, implementation limits, and practitioner perceptions." },
  SE53: { title: "Hanson & Bussière — Predictor Meta-Analysis", organization: "Research / Public Safety Canada", type: "Research / government-hosted publication", href: "https://www.publicsafety.gc.ca/cnt/rsrcs/pblctns/prdctrs-sxl-ffnd/index-en.aspx", usefulFor: "Foundational meta-analysis of factors associated with sexual-offense recidivism and the heterogeneity of risk." },
  SE54: { title: "Hanson & Morton-Bourgon — Updated Predictors", organization: "Research / Public Safety Canada", type: "Research / government-hosted publication", href: "https://www.publicsafety.gc.ca/cnt/rsrcs/pblctns/2004-02-prdctrs-sxl-rcdvsm-pdtd/index-en.aspx", usefulFor: "Updated meta-analysis of characteristics associated with persistent sexual offending and structured risk assessment." },
  SE55: { title: "Hanson — Sex Offender Recidivism: A Simple Question", organization: "Public Safety Canada", type: "Government-hosted research summary", href: "https://www.publicsafety.gc.ca/cnt/rsrcs/pblctns/sx-ffndr-rcdvsm/index-en.aspx", usefulFor: "Plain-language synthesis explaining why observed sexual recidivism varies by subgroup, follow-up period, age, and prior history." },
  SE56: { title: "Babchishin, Hanson & Helmus — Risk-Assessment Accuracy", organization: "Peer-reviewed research", type: "Peer-reviewed article", href: "https://pubmed.ncbi.nlm.nih.gov/19290762/", usefulFor: "Meta-analytic evidence comparing actuarial, structured, and unstructured approaches to predicting sexual recidivism." },
  SE57: { title: "Static-99R — Coding Rules", organization: "Professional risk-assessment guidance", type: "Professional guidance", href: "https://www.waspc.org/assets/Static%2099%20Coding_manual_2016_v2.pdf", usefulFor: "Professional guidance on Static-99R eligibility, coding, scoring, age adjustments, and proper instrument use." },
  SE58: { title: "Static-99R — Evaluators Workbook", organization: "Professional risk-assessment guidance", type: "Professional guidance", href: "https://www.oregon.gov/boppps/Documents/R%26R/Static%20Evaluators_Workbook_2021-09-28.pdf", usefulFor: "Guidance on reference groups, relative risk, absolute estimates, and the limits of interpreting actuarial scores." },
  SE59: { title: "PCRA — Construction and Validation", organization: "Federal Probation / U.S. Courts", type: "Government journal article", href: "https://www.uscourts.gov/about-federal-courts/probation-and-pretrial-services/federal-probation-journal/2011/09/construction-and-validation-federal-post-conviction-risk-assessment-pcra", usefulFor: "Federal evidence on the PCRA as a general post-conviction risk-and-needs instrument, useful for distinguishing general from specialized sexual-risk questions." },
  SE60: { title: "CPORT — Development Study", organization: "Peer-reviewed research", type: "Peer-reviewed article", href: "https://pubmed.ncbi.nlm.nih.gov/25844514/", usefulFor: "Development evidence for a CSEM-specific empirical risk tool and the distinction between specialized and general risk assessment." },
  SE61: { title: "CPORT — Validation Study", organization: "Peer-reviewed research", type: "Peer-reviewed article", href: "https://pubmed.ncbi.nlm.nih.gov/29592774/", usefulFor: "Validation evidence for CPORT in adult male CSEM populations, including discrimination and population-fit questions." },
  SE62: { title: "CPORT — Critical Review", organization: "Peer-reviewed research", type: "Peer-reviewed article", href: "https://pubmed.ncbi.nlm.nih.gov/37471014/", usefulFor: "Critical review identifying limitations in the evidence base for using CPORT in U.S. CSEM-exclusive forensic settings." },
  SE63: { title: "STABLE-2007 — Prospective Study", organization: "Peer-reviewed research", type: "Peer-reviewed article", href: "https://doi.org/10.1177/0093854815602094", usefulFor: "Prospective evidence on structured dynamic risk factors, change over time, and recidivism." },
  SE64: { title: "SOTIPS — Validation Study", organization: "Peer-reviewed research", type: "Peer-reviewed article", href: "https://pubmed.ncbi.nlm.nih.gov/22368161/", usefulFor: "Validation evidence for a structured dynamic-risk and treatment-progress instrument." },
  SE65: { title: "VRS-SO — Validity and Reliability", organization: "Peer-reviewed research", type: "Peer-reviewed article", href: "https://pubmed.ncbi.nlm.nih.gov/17845123/", usefulFor: "Evidence on structured assessment of risk, treatment targets, and therapeutic change." },
  SE66: { title: "Schmucker & Lösel — Treatment Meta-Analysis", organization: "Journal of Experimental Criminology", type: "Peer-reviewed meta-analysis", href: "https://doi.org/10.1007/s11292-015-9241-z", usefulFor: "Meta-analytic evidence on specialized treatment and sexual-recidivism outcomes." },
  SE67: { title: "Does #1–5 v. Snyder", organization: "U.S. Court of Appeals for the Sixth Circuit", type: "Federal appellate decision", href: "https://law.justia.com/cases/federal/appellate-courts/ca6/15-1536/15-1536-2016-08-25.html", usefulFor: "Sixth Circuit decision holding Michigan's amended registry punitive in effect for ex post facto purposes, illustrating that modern schemes are assessed on their actual effects." },
};
