backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"   # where uploaded images/files are stored
public_folder: "/uploads"        # how the site links to them

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "public/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "guides"
    label: "Resource Guides"
    folder: "public/content/guides"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Updated", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
