import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const ROOT = process.cwd();
const SITE_ORIGIN = 'https://thesolarproject.org';
const OUTPUT = path.join(ROOT, 'public', 'sitemap.xml');

const EXCLUDED_STATIC_ROUTES = new Set([
  '/resources/resource-guide-sandbox',
]);

function isIndexableStaticRoute(route) {
  return (
    route.startsWith('/') &&
    !route.includes(':') &&
    !route.includes('*') &&
    !EXCLUDED_STATIC_ROUTES.has(route)
  );
}

function xmlEscape(value) {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');
}

async function collectStaticAppRoutes() {
  const source = await readFile(path.join(ROOT, 'src', 'App.tsx'), 'utf8');
  const routes = new Set();
  const routePattern = /<Route\b[^>]*\bpath=["']([^"']+)["'][^>]*>/g;

  for (const match of source.matchAll(routePattern)) {
    const route = match[1];
    if (isIndexableStaticRoute(route)) routes.add(route);
  }

  return routes;
}

async function collectStateRegistryRoutes() {
  const dir = path.join(ROOT, 'src', 'data', 'state-registry');
  const entries = await readdir(dir, { withFileTypes: true });
  return new Set(
    entries
      .filter((entry) => entry.isFile() && /^[a-z]{2}\.(?:ts|json)$/.test(entry.name))
      .map((entry) => `/resources/state-registry/states/${entry.name.slice(0, 2)}`),
  );
}

async function collectAccountabilityWatchRoutes() {
  const routes = new Set();
  const dir = path.join(ROOT, 'src', 'pages', 'resources', 'accountability-watch');
  const entries = await readdir(dir, { withFileTypes: true });

  for (const entry of entries) {
    const match = entry.isFile() && entry.name.match(/^(\d{4}-\d{2}-\d{2})\.tsx$/);
    if (match) routes.add(`/resources/accountability-watch/${match[1]}`);
  }

  // The data file is also a canonical publishing surface. Include any published
  // paths declared there even if a future page implementation changes shape.
  const data = await readFile(path.join(ROOT, 'src', 'data', 'accountabilityWatch.ts'), 'utf8');
  const pathPattern = /\bpath:\s*["'`]([^"'`]+)["'`]/g;
  for (const match of data.matchAll(pathPattern)) {
    if (match[1].startsWith('/resources/accountability-watch/')) routes.add(match[1]);
  }

  return routes;
}

async function collectLegislativeTrackerRoutes() {
  const routes = new Set();
  const dir = path.join(ROOT, 'src', 'pages', 'resources', 'legislative-tracker');
  const entries = await readdir(dir, { withFileTypes: true });

  for (const entry of entries) {
    const match = entry.isFile() && entry.name.match(/^(\d{4})-(\d{2})-(\d{2})\.tsx$/);
    if (!match) continue;

    const year = Number(match[1]);
    // 2099 files are internal scaffold/preview pages and must never enter search.
    if (year >= 2099) continue;

    routes.add(`/resources/legislative-tracker/${match[1]}-${match[2]}-${match[3]}`);
  }

  return routes;
}

const routeGroups = await Promise.all([
  collectStaticAppRoutes(),
  collectStateRegistryRoutes(),
  collectAccountabilityWatchRoutes(),
  collectLegislativeTrackerRoutes(),
]);

const routes = new Set();
for (const group of routeGroups) {
  for (const route of group) routes.add(route);
}

const orderedRoutes = [...routes].sort((a, b) => {
  if (a === '/') return -1;
  if (b === '/') return 1;
  return a.localeCompare(b);
});

const urls = orderedRoutes
  .map((route) => `  <url><loc>${xmlEscape(`${SITE_ORIGIN}${route}`)}</loc></url>`)
  .join('\n');

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Generated by scripts/generate-sitemap.mjs. Do not edit by hand. -->\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`;

await writeFile(OUTPUT, sitemap, 'utf8');
console.log(`Generated sitemap with ${orderedRoutes.length} canonical URLs.`);
